language: ruby
rvm:
  - "2.1.2"
before_script: bundle exec rake gems:install db:setup test
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
