source 'https://rubygems.org'

gem 'rails', '2.3.18', require: nil

gem 'sqlite3', require: 'sqlite3'
gem 'will_paginate', '2.3.16' # Don't use '3.x.x' # LOCKED DOWN
gem 'iconv'
gem 'faker'
gem 'i18n'

gem 'rake'

group :development do
  gem 'rails-footnotes'
end

group :test do
  gem 'rspec'
  gem 'test-unit'
end

######################################################################
# Devise 1.0.2 is not a valid gem plugin for Rails, so use git until 1.0.3
# gem 'devise', :git => 'git://github.com/plataformatec/devise.git', :ref => 'v1.0'
